name: Jekyll site CI

on:
  push:
    branches:  master 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
      
    - name: Login to Docker hub
      uses: docker/login-action@v1
      with:
        name: pungpeeecicd/repository
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


      
  non-deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v1
         name: executing remote ssh commands using ssh key
         with: 
          hosts: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          script: whoami
          command: |
             cd test-cicd-firstTime         
        
  deploy:
    needs: non-deploy
    runs-on: ubuntu-latest
    steps:
    - uses: docker/build-push-action@v2
    - run: |
        using: 'docker'
        image: 'Dockerfile'
