name: Jekyll site CI

on:
  push:
    branches:  master 

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set env
        run: echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/master" ] && echo 'uat' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV
      
      - uses: docker/build-push-action@v2
        name: docker build-run
        with: 
          command:
            docker build -t nginx:alpine -f ./Dockerfile .
            
      - name: Login to Github Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN_GITHUB }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/pungpeee/test-cicd-firsttime:${{ env.ENV_NAME }}          
        
  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: appleboy/ssh-action@master
        name: Login and Deploy execute command ssh to remote server
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
         port: 22
         script: |
            ls -la


