name: jekyll

on:
  push:
    branches:  master 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build with jekyll
    - uses:  actions/checkout@v2
    - uses: kshehadeh/jekyll-s3-action@220371747871b9aa1b635fb30a57693891e37982
    - uses: kshehadeh/jekyll-s3-action@0.1
