name: Azure Login

on:
  push:
    branches:  master 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the site in the azure login
      uses: azure/login@v1
      with: 
        creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
