name: Jekyll site CI

on:
  push:
    branches:  master 

jobs:
  build:

    runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Build the site in the jekyll/builder container
#       run: |
#         docker run \
#         -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
#         jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
      
#     - name: Login to Docker hub
#       uses: docker/login-action@v1
#       with:
#         name: pungpeeecicd/repository
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}


      
  non-deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
       - uses: docker/build-push-action@v2
         name: docker build-run
       - run: |
           pwd      
        
#   deploy:
#     needs: non-deploy
#     runs-on: ubuntu-latest
#     steps:
#     - uses: JimCronqvist/action-ssh@master
#       name: Deploy execute command ssh to remote server
#       with:
#        hosts: ${{ secrets.HOST }}
#        publicKey: ${{ secrets.SSH_PUBLIC_KEY }}
#        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
#        command: |
#           pwd
#           ls -la


