name: jekyll

on:
  push:
    branches:  master 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build with jekyll
    - uses:  helaili/jekyll-action@v2
      with:
        credentials: ${{ secrets.AZURE_CREDENTIALS }}
